### ISSUE TITLE
"latest" release doesn't include the latest PR

### ISSUE THREAD

**Issue by rickgladwin** [shan-shaji/ansi-escapes-dart#3]
Running `dart pub add ansi_escapes` adds a version of the package before the "curserTo --> cursorTo" change from pull request #2 

Can you update the package version number either to 1.1.0 or 2.0.0 and run `dart pub publish`?

**Comment by shan-shaji** [comment]
@rickgladwin  really sorry for the late reply. I have released the new version of the package. Closing this issue for now.
